### PR TITLE
Add missing extern C

### PR DESCRIPTION
**Pull request by mark0n**
Patch provided by Eric Bjorklund.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
As a note, this also involves EPICS Base since the MMIO headers are included in >= 3.15.0.2.

**Comment by mdavidsaver** [comment]
https://bugs.launchpad.net/epics-base/+bug/1531359

**Comment by mdavidsaver** [comment]
You fooled me Martin :)  Bug fixes should go here first https://github.com/epics-modules/devlib2

**Comment by mdavidsaver** [comment]
And there is no reason to apply vxWorks specific fixes.

**Comment by mark0n** [comment]
Oops, wrong repo - sorry about that...

**Pull request merged**
